// SPDX-License-Identifier: GPL-3.0-or-later

package jwtissuer

import (
	"crypto"
	"crypto/ecdh"
	"crypto/ecdsa"
	"crypto/ed25519"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"encoding/pem"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// writePEM writes one PEM block to a fresh file and returns its path.
func writePEM(t *testing.T, blockType string, der []byte) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "key.pem")
	data := pem.EncodeToMemory(&pem.Block{Type: blockType, Bytes: der})
	if err := os.WriteFile(path, data, 0o600); err != nil {
		t.Fatalf("write key file: %v", err)
	}
	return path
}

func pkcs8(t *testing.T, key crypto.PrivateKey) []byte {
	t.Helper()
	der, err := x509.MarshalPKCS8PrivateKey(key)
	if err != nil {
		t.Fatalf("marshal PKCS#8: %v", err)
	}
	return der
}

func pkix(t *testing.T, key crypto.PublicKey) []byte {
	t.Helper()
	der, err := x509.MarshalPKIXPublicKey(key)
	if err != nil {
		t.Fatalf("marshal PKIX: %v", err)
	}
	return der
}

func mustECDSA(t *testing.T, curve elliptic.Curve) *ecdsa.PrivateKey {
	t.Helper()
	k, err := ecdsa.GenerateKey(curve, rand.Reader)
	if err != nil {
		t.Fatalf("generate EC key: %v", err)
	}
	return k
}

func mustEd25519(t *testing.T) ed25519.PrivateKey {
	t.Helper()
	_, k, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("generate Ed25519 key: %v", err)
	}
	return k
}

func mustRSA(t *testing.T, bits int) *rsa.PrivateKey {
	t.Helper()
	k, err := rsa.GenerateKey(rand.Reader, bits)
	if err != nil {
		t.Fatalf("generate RSA-%d key: %v", bits, err)
	}
	return k
}

// Spec forgejo-jwt-issuer: "The signing key's type determines the algorithm".
func TestKeyTypeDeterminesAlgorithm(t *testing.T) {
	cases := []struct {
		name string
		key  crypto.PrivateKey
		alg  string
	}{
		{"EC P-256", mustECDSA(t, elliptic.P256()), "ES256"},
		{"EC P-384", mustECDSA(t, elliptic.P384()), "ES384"},
		{"Ed25519", mustEd25519(t), "EdDSA"},
		{"RSA 2048", mustRSA(t, 2048), "RS256"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			k, err := LoadSigningKey(writePEM(t, "PRIVATE KEY", pkcs8(t, tc.key)))
			if err != nil {
				t.Fatalf("LoadSigningKey: %v", err)
			}
			if got := k.Algorithm(); got != tc.alg {
				t.Fatalf("algorithm = %q, want %q", got, tc.alg)
			}
		})
	}
}

// Spec forgejo-jwt-issuer, scenario "Unsupported key": the start is refused
// with a message naming the file.
func TestUnsupportedKeysAreRefusedNamingTheFile(t *testing.T) {
	x25519, err := ecdh.X25519().GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("generate X25519 key: %v", err)
	}
	cases := []struct {
		name string
		key  crypto.PrivateKey
		want string
	}{
		{"RSA 1024", mustRSA(t, 1024), "at least 2048"},
		{"EC P-521", mustECDSA(t, elliptic.P521()), "P-256 or P-384"},
		{"X25519", x25519, "unsupported key type"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			path := writePEM(t, "PRIVATE KEY", pkcs8(t, tc.key))
			_, err := LoadSigningKey(path)
			if err == nil {
				t.Fatal("LoadSigningKey accepted an unsupported key")
			}
			if !strings.Contains(err.Error(), path) || !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("error %q does not name %q and %q", err, path, tc.want)
			}
		})
	}
}

// A signing key file with only a public key cannot sign; a published key may
// be public.
func TestSigningKeyMustBePrivate(t *testing.T) {
	path := writePEM(t, "PUBLIC KEY", pkix(t, mustEd25519(t).Public()))

	if _, err := LoadSigningKey(path); err == nil || !strings.Contains(err.Error(), path) {
		t.Fatalf("LoadSigningKey(public) error = %v, want a refusal naming the file", err)
	}
	k, err := LoadPublishedKey(path)
	if err != nil {
		t.Fatalf("LoadPublishedKey(public): %v", err)
	}
	if k.signer != nil {
		t.Fatal("a public key must not yield a signer")
	}
}

// Keys generated by common tooling arrive in the older SEC 1 and PKCS#1
// encodings as often as in PKCS#8.
func TestLegacyPrivateKeyEncodingsAreAccepted(t *testing.T) {
	ec := mustECDSA(t, elliptic.P256())
	ecDER, err := x509.MarshalECPrivateKey(ec)
	if err != nil {
		t.Fatalf("marshal SEC 1: %v", err)
	}
	if _, err := LoadSigningKey(writePEM(t, "EC PRIVATE KEY", ecDER)); err != nil {
		t.Fatalf("SEC 1 EC key: %v", err)
	}

	rsaKey := mustRSA(t, 2048)
	if _, err := LoadSigningKey(writePEM(t, "RSA PRIVATE KEY", x509.MarshalPKCS1PrivateKey(rsaKey))); err != nil {
		t.Fatalf("PKCS#1 RSA key: %v", err)
	}
}

func TestUnreadableOrMalformedKeyFilesAreRefused(t *testing.T) {
	dir := t.TempDir()
	write := func(name, content string) string {
		p := filepath.Join(dir, name)
		if err := os.WriteFile(p, []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
		return p
	}
	block := string(pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: pkcs8(t, mustEd25519(t))}))

	cases := map[string]string{
		"missing file":      filepath.Join(dir, "absent.pem"),
		"not PEM":           write("garbage.pem", "not a key"),
		"two PEM blocks":    write("two.pem", block+block),
		"encrypted PKCS#8":  write("enc.pem", string(pem.EncodeToMemory(&pem.Block{Type: "ENCRYPTED PRIVATE KEY", Bytes: []byte{1}}))),
		"unknown PEM block": write("cert.pem", string(pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: []byte{1}}))),
	}
	for name, path := range cases {
		t.Run(name, func(t *testing.T) {
			_, err := LoadPublishedKey(path)
			if err == nil {
				t.Fatal("malformed key file was accepted")
			}
			if !strings.Contains(err.Error(), path) {
				t.Fatalf("error %q does not name %q", err, path)
			}
		})
	}
}

// The key ID is the RFC 7638 thumbprint, computed here independently of the
// JOSE library from the canonical JSON members of an EC public key.
func TestKeyIDIsTheRFC7638Thumbprint(t *testing.T) {
	ec := mustECDSA(t, elliptic.P256())
	k, err := LoadSigningKey(writePEM(t, "PRIVATE KEY", pkcs8(t, ec)))
	if err != nil {
		t.Fatalf("LoadSigningKey: %v", err)
	}

	pub, err := ec.PublicKey.ECDH()
	if err != nil {
		t.Fatalf("ECDH public key: %v", err)
	}
	point := pub.Bytes() // 0x04 || X || Y, each 32 bytes for P-256
	x, y := point[1:33], point[33:65]
	canonical := fmt.Sprintf(`{"crv":"P-256","kty":"EC","x":"%s","y":"%s"}`,
		base64.RawURLEncoding.EncodeToString(x), base64.RawURLEncoding.EncodeToString(y))
	sum := sha256.Sum256([]byte(canonical))
	want := base64.RawURLEncoding.EncodeToString(sum[:])

	if got := k.KeyID(); got != want {
		t.Fatalf("key ID = %q, want RFC 7638 thumbprint %q", got, want)
	}
}

// The same key loaded as a private and as a public key has the same key ID, so
// staging a public key and later signing with its private half line up.
func TestKeyIDDoesNotDependOnWhichHalfWasLoaded(t *testing.T) {
	ed := mustEd25519(t)
	priv, err := LoadSigningKey(writePEM(t, "PRIVATE KEY", pkcs8(t, ed)))
	if err != nil {
		t.Fatal(err)
	}
	pub, err := LoadPublishedKey(writePEM(t, "PUBLIC KEY", pkix(t, ed.Public())))
	if err != nil {
		t.Fatal(err)
	}
	if priv.KeyID() != pub.KeyID() {
		t.Fatalf("key IDs differ: private %q, public %q", priv.KeyID(), pub.KeyID())
	}
}
